//! GTM Landing Page Engine — discriminant enums
//!
//! All string-backed fields on `platform_products`, `product_page_variants`,
//! `product_tracking_pixels`, and `pub_products` lead-capture are expressed
//! here as proper Rust enums so the compiler enforces exhaustive match and
//! serde rejects unknown variants at deserialization boundaries.
//!
//! Pattern follows the existing codebase conventions in `types/lead.rs` and
//! `types/account.rs`:
//!   - `#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]`
//!   - `#[serde(rename_all = "snake_case")]` on the enum level
//!   - `impl Display` mapping each variant to its DB string
//!   - `impl TryFrom<String>` returning `Err(String)` on unknown discriminants

use serde::{Deserialize, Serialize};
use std::fmt;

// ── LaunchMode ────────────────────────────────────────────────────────────────

/// Controls what a visitor sees when they land on a product page.
///
/// Stored as VARCHAR in `platform_products.launch_mode` and
/// `product_page_variants.launch_mode`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LaunchMode {
    /// Product is fully live — show CTA to sign up / subscribe.
    Active,
    /// Product is in pre-launch — collect email for waitlist.
    Waitlist,
    /// Product is available for pre-order with Stripe Checkout.
    PreOrder,
    /// Internal soft-launch phase — shown only to approved testers.
    PreLaunch,
    /// Not yet ready for any traffic. Renders 404 / coming-soon.
    Draft,
}

impl LaunchMode {
    /// Returns `true` if visitors can complete a conversion action on the page.
    pub fn allows_conversion(&self) -> bool {
        matches!(self, Self::Active | Self::PreOrder | Self::Waitlist)
    }

    /// Returns `true` if the page should be indexed by search engines.
    pub fn is_indexable(&self) -> bool {
        matches!(self, Self::Active | Self::Waitlist | Self::PreOrder)
    }
}

impl fmt::Display for LaunchMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Active => "active",
            Self::Waitlist => "waitlist",
            Self::PreOrder => "pre_order",
            Self::PreLaunch => "pre_launch",
            Self::Draft => "draft",
        })
    }
}

impl TryFrom<String> for LaunchMode {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "active" => Ok(Self::Active),
            "waitlist" => Ok(Self::Waitlist),
            "pre_order" => Ok(Self::PreOrder),
            "pre_launch" => Ok(Self::PreLaunch),
            "draft" => Ok(Self::Draft),
            other => Err(format!("unknown LaunchMode: '{other}'")),
        }
    }
}

impl TryFrom<&str> for LaunchMode {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── LocalizationStatus ────────────────────────────────────────────────────────

/// Tracks how a product page variant's copy was created / last modified.
///
/// Stored as VARCHAR in `product_page_variants.localization_status`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LocalizationStatus {
    /// Uses the base template copy — no market-specific overrides.
    Base,
    /// Copy was generated by the AI localization pipeline.
    AiLocalized,
    /// Copy was written or reviewed by a human marketer.
    Manual,
    /// AI localization task has been dispatched but not yet completed.
    Pending,
}

impl LocalizationStatus {
    /// Returns `true` if a human has reviewed or authored the copy.
    pub fn is_human_reviewed(&self) -> bool {
        matches!(self, Self::Manual)
    }
}

impl fmt::Display for LocalizationStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Base => "base",
            Self::AiLocalized => "ai_localized",
            Self::Manual => "manual",
            Self::Pending => "pending",
        })
    }
}

impl TryFrom<String> for LocalizationStatus {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "base" => Ok(Self::Base),
            "ai_localized" => Ok(Self::AiLocalized),
            "manual" => Ok(Self::Manual),
            "pending" => Ok(Self::Pending),
            other => Err(format!("unknown LocalizationStatus: '{other}'")),
        }
    }
}

impl TryFrom<&str> for LocalizationStatus {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── CopyStrategy ──────────────────────────────────────────────────────────────

/// The approach used when generating this variant's copy.
///
/// Stored as VARCHAR in `product_page_variants.copy_strategy`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CopyStrategy {
    /// Market-specific copy: city, neighbourhood, local social proof.
    Localized,
    /// Verbatim copy from the base product template.
    BaseCopy,
    /// AI-generated using geo-context signals and product brief.
    AiGenerated,
}

impl fmt::Display for CopyStrategy {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Localized => "localized",
            Self::BaseCopy => "base_copy",
            Self::AiGenerated => "ai_generated",
        })
    }
}

impl TryFrom<String> for CopyStrategy {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "localized" => Ok(Self::Localized),
            "base_copy" => Ok(Self::BaseCopy),
            "ai_generated" => Ok(Self::AiGenerated),
            other => Err(format!("unknown CopyStrategy: '{other}'")),
        }
    }
}

impl TryFrom<&str> for CopyStrategy {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── PixelType ─────────────────────────────────────────────────────────────────

/// The analytics / advertising platform a tracking snippet belongs to.
///
/// Stored as VARCHAR in `product_tracking_pixels.pixel_type` with a
/// CHECK constraint matching each variant's Display string.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PixelType {
    /// Google Tag Manager container.
    Gtm,
    /// Google Analytics 4 measurement ID (G-XXXXXXXX).
    Ga4,
    /// Meta (Facebook) Pixel.
    Meta,
    /// LinkedIn Insight Tag.
    Linkedin,
    /// TikTok Pixel.
    Tiktok,
    /// Any custom <script> or <noscript> block.
    Custom,
}

impl PixelType {
    /// Returns `true` if this pixel type requires a separate `<noscript>` fallback.
    pub fn needs_noscript_fallback(&self) -> bool {
        matches!(self, Self::Meta | Self::Linkedin)
    }
}

impl fmt::Display for PixelType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Gtm => "gtm",
            Self::Ga4 => "ga4",
            Self::Meta => "meta",
            Self::Linkedin => "linkedin",
            Self::Tiktok => "tiktok",
            Self::Custom => "custom",
        })
    }
}

impl TryFrom<String> for PixelType {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "gtm" => Ok(Self::Gtm),
            "ga4" => Ok(Self::Ga4),
            "meta" => Ok(Self::Meta),
            "linkedin" => Ok(Self::Linkedin),
            "tiktok" => Ok(Self::Tiktok),
            "custom" => Ok(Self::Custom),
            other => Err(format!("unknown PixelType: '{other}'")),
        }
    }
}

impl TryFrom<&str> for PixelType {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── InjectAt ──────────────────────────────────────────────────────────────────

/// Where in the HTML document a tracking snippet is injected.
///
/// Stored as VARCHAR in `product_tracking_pixels.inject_at`.
/// The SSR renderer reads this field to determine placement.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InjectAt {
    /// Inside `<head>` — recommended for most pixels (GTM, GA4, Meta).
    Head,
    /// Immediately after `<body>` opening tag.
    BodyStart,
    /// Immediately before `</body>` closing tag — for low-priority scripts.
    BodyEnd,
}

impl fmt::Display for InjectAt {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Head => "head",
            Self::BodyStart => "body_start",
            Self::BodyEnd => "body_end",
        })
    }
}

impl TryFrom<String> for InjectAt {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "head" => Ok(Self::Head),
            "body_start" => Ok(Self::BodyStart),
            "body_end" => Ok(Self::BodyEnd),
            other => Err(format!("unknown InjectAt: '{other}'")),
        }
    }
}

impl TryFrom<&str> for InjectAt {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── PlanTier ──────────────────────────────────────────────────────────────────

/// Self-reported plan tier selected during a waitlist or trial signup.
///
/// Stored in `atlas_lead.lead_metadata` JSONB under the key `"plan"`.
/// Not persisted as a VARCHAR column because: (a) it's attribution metadata,
/// not a billing commitment; (b) pricing tiers change more often than DB schemas.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanTier {
    Starter,
    Professional,
    Portfolio,
}

impl PlanTier {
    /// Returns `true` if this tier suggests a high-value prospect worth
    /// immediate SDR follow-up (≥ Professional).
    pub fn is_high_value(&self) -> bool {
        matches!(self, Self::Professional | Self::Portfolio)
    }
}

impl fmt::Display for PlanTier {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Starter => "starter",
            Self::Professional => "professional",
            Self::Portfolio => "portfolio",
        })
    }
}

impl TryFrom<String> for PlanTier {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "starter" => Ok(Self::Starter),
            "professional" => Ok(Self::Professional),
            "portfolio" => Ok(Self::Portfolio),
            other => Err(format!("unknown PlanTier: '{other}'")),
        }
    }
}

impl TryFrom<&str> for PlanTier {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── ResolutionType ────────────────────────────────────────────────────────────

/// The outcome of a domain/path resolution request.
///
/// Used in `handlers::pub_resolve::ResolveResponse` to let the Folio
/// frontend know which rendering path to take.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResolutionType {
    /// Resolved to a product-level master template page.
    Product,
    /// Resolved to a specific market variant page.
    Variant,
    /// Resolved to a tenant white-label app deployment.
    TenantApp,
    /// No product, variant, or tenant matched the request.
    NotFound,
}

impl fmt::Display for ResolutionType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Product => "product",
            Self::Variant => "variant",
            Self::TenantApp => "tenant_app",
            Self::NotFound => "not_found",
        })
    }
}

impl TryFrom<String> for ResolutionType {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "product" => Ok(Self::Product),
            "variant" => Ok(Self::Variant),
            "tenant_app" => Ok(Self::TenantApp),
            "not_found" => Ok(Self::NotFound),
            other => Err(format!("unknown ResolutionType: '{other}'")),
        }
    }
}

impl TryFrom<&str> for ResolutionType {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── AppId ──────────────────────────────────────────────────────────────────────

/// Identifies which Atlas app binary owns a given `platform_product`.
///
/// Values mirror the `&'static str` returned by each `AtlasApp::app_id()` impl.
/// Stored as `platform_products.app_slug` so the edge resolver can route
/// a domain request to the correct app SSR binary without slug-guessing.
///
/// # Keeping in sync
/// When a new `AtlasApp` impl is added in `atlas_apps/`, add its `app_id()` value
/// here AND update the DB CHECK constraint in the migration. The compiler will
/// flag every non-exhaustive match site automatically.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AppId {
    /// `FolioApp` — property management (LTR, STR, wholesaling)
    PropertyManagement,
    /// `AnchorApp` — anchor pages / classified directory
    Anchor,
    /// `NetworkInstanceApp` — network instance (portals, B2B directories)
    NetworkInstance,
    /// `MeridianApp` — hospitality / direct booking engine
    Meridian,
    /// `CorePlatformApp` — platform infrastructure (used for meta-products)
    CorePlatform,
}

impl AppId {
    /// The canonical string stored in the DB and returned in API responses.
    ///
    /// These must match the corresponding `AtlasApp::app_id()` return values.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::PropertyManagement => "property_management",
            Self::Anchor => "anchor",
            Self::NetworkInstance => "network_instance",
            Self::Meridian => "meridian",
            Self::CorePlatform => "core_platform",
        }
    }

    /// All valid DB values — used to generate the CHECK constraint in migrations.
    pub fn all_db_values() -> &'static [&'static str] {
        &[
            "property_management",
            "anchor",
            "network_instance",
            "meridian",
            "core_platform",
        ]
    }

    /// The marketing-facing slug used in URLs and product records.
    /// e.g. `PropertyManagement → "folio"`.
    pub fn product_slug(&self) -> &'static str {
        match self {
            Self::PropertyManagement => "folio",
            Self::Anchor => "anchor",
            Self::NetworkInstance => "network_instance",
            Self::Meridian => "meridian",
            Self::CorePlatform => "core",
        }
    }
}

impl fmt::Display for AppId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<String> for AppId {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "property_management" => Ok(Self::PropertyManagement),
            "anchor" => Ok(Self::Anchor),
            "network_instance" => Ok(Self::NetworkInstance),
            "meridian" => Ok(Self::Meridian),
            "core_platform" => Ok(Self::CorePlatform),
            other => Err(format!("unknown AppId: '{other}'")),
        }
    }
}

impl TryFrom<&str> for AppId {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── MarketingSectionBlockType ─────────────────────────────────────────────────
// Keep variants/strings aligned with `shared_ui::marketing::MarketingSectionBlockType`.

/// CMS section block `type` values accepted in `blocks_payload`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MarketingSectionBlockType {
    Stats,
    FeatureGrid,
    Personas,
    Cta,
    BetaStrip,
    Markets,
    PaymentRails,
    StrSection,
    TenantPortal,
    OwnerPortal,
    Footer,
    NavSections,
    PricingIntro,
    TradeCategories,
    RichText,
    Hero,
    FullPage,
}

impl MarketingSectionBlockType {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Stats => "stats",
            Self::FeatureGrid => "feature_grid",
            Self::Personas => "personas",
            Self::Cta => "cta",
            Self::BetaStrip => "beta_strip",
            Self::Markets => "markets",
            Self::PaymentRails => "payment_rails",
            Self::StrSection => "str_section",
            Self::TenantPortal => "tenant_portal",
            Self::OwnerPortal => "owner_portal",
            Self::Footer => "footer",
            Self::NavSections => "nav_sections",
            Self::PricingIntro => "pricing_intro",
            Self::TradeCategories => "trade_categories",
            Self::RichText => "rich_text",
            Self::Hero => "hero",
            Self::FullPage => "full_page",
        }
    }
}

impl fmt::Display for MarketingSectionBlockType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for MarketingSectionBlockType {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s {
            "stats" => Ok(Self::Stats),
            "feature_grid" => Ok(Self::FeatureGrid),
            "personas" => Ok(Self::Personas),
            "cta" => Ok(Self::Cta),
            "beta_strip" => Ok(Self::BetaStrip),
            "markets" => Ok(Self::Markets),
            "payment_rails" => Ok(Self::PaymentRails),
            "str_section" => Ok(Self::StrSection),
            "tenant_portal" => Ok(Self::TenantPortal),
            "owner_portal" => Ok(Self::OwnerPortal),
            "footer" => Ok(Self::Footer),
            "nav_sections" => Ok(Self::NavSections),
            "pricing_intro" => Ok(Self::PricingIntro),
            "trade_categories" => Ok(Self::TradeCategories),
            "rich_text" => Ok(Self::RichText),
            "hero" => Ok(Self::Hero),
            "full_page" => Ok(Self::FullPage),
            other => Err(format!("unknown MarketingSectionBlockType: '{other}'")),
        }
    }
}

// ── FolioMarketingSlug ────────────────────────────────────────────────────────
// Keep aligned with `shared_ui::marketing::FolioMarketingSlug`.

/// Folio public marketing product / landing slugs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FolioMarketingSlug {
    #[serde(rename = "folio")]
    Folio,
    #[serde(rename = "folio-broker")]
    FolioBroker,
    #[serde(rename = "folio-pm")]
    FolioPm,
    #[serde(rename = "folio-vendor")]
    FolioVendor,
    #[serde(rename = "folio-founding")]
    FolioFounding,
    #[serde(rename = "folio-beta")]
    FolioBeta,
    #[serde(rename = "folio-cohost-market")]
    FolioCohostMarket,
}

impl FolioMarketingSlug {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Folio => "folio",
            Self::FolioBroker => "folio-broker",
            Self::FolioPm => "folio-pm",
            Self::FolioVendor => "folio-vendor",
            Self::FolioFounding => "folio-founding",
            Self::FolioBeta => "folio-beta",
            Self::FolioCohostMarket => "folio-cohost-market",
        }
    }

    pub fn public_path(self) -> &'static str {
        match self {
            Self::Folio => "/",
            Self::FolioBroker => "/brokers",
            Self::FolioPm => "/property-managers",
            Self::FolioVendor => "/vendors",
            Self::FolioFounding => "/founding",
            Self::FolioBeta => "/beta",
            Self::FolioCohostMarket => "/cohost-market",
        }
    }

    pub fn waitlist_lead_source(self) -> String {
        format!("waitlist:{}", self.as_str())
    }
}

impl fmt::Display for FolioMarketingSlug {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for FolioMarketingSlug {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s {
            "folio" => Ok(Self::Folio),
            "folio-broker" => Ok(Self::FolioBroker),
            "folio-pm" => Ok(Self::FolioPm),
            "folio-vendor" => Ok(Self::FolioVendor),
            "folio-founding" => Ok(Self::FolioFounding),
            "folio-beta" => Ok(Self::FolioBeta),
            "folio-cohost-market" => Ok(Self::FolioCohostMarket),
            other => Err(format!("unknown FolioMarketingSlug: '{other}'")),
        }
    }
}

// ── FoundingSpotTier ──────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FoundingSpotTier {
    #[serde(rename = "ll-grow")]
    LlGrow,
    #[serde(rename = "ll-pro")]
    LlPro,
    #[serde(rename = "ll-investor")]
    LlInvestor,
    #[serde(rename = "br-solo")]
    BrSolo,
    #[serde(rename = "br-team")]
    BrTeam,
    #[serde(rename = "br-firm")]
    BrFirm,
    #[serde(rename = "pm-starter")]
    PmStarter,
    #[serde(rename = "pm-growth")]
    PmGrowth,
    #[serde(rename = "vd-pro")]
    VdPro,
}

impl FoundingSpotTier {
    pub const ALL: &'static [Self] = &[
        Self::LlGrow,
        Self::LlPro,
        Self::LlInvestor,
        Self::BrSolo,
        Self::BrTeam,
        Self::BrFirm,
        Self::PmStarter,
        Self::PmGrowth,
        Self::VdPro,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::LlGrow => "ll-grow",
            Self::LlPro => "ll-pro",
            Self::LlInvestor => "ll-investor",
            Self::BrSolo => "br-solo",
            Self::BrTeam => "br-team",
            Self::BrFirm => "br-firm",
            Self::PmStarter => "pm-starter",
            Self::PmGrowth => "pm-growth",
            Self::VdPro => "vd-pro",
        }
    }
}

impl fmt::Display for FoundingSpotTier {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for FoundingSpotTier {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::ALL
            .iter()
            .copied()
            .find(|v| v.as_str() == s)
            .ok_or_else(|| format!("unknown FoundingSpotTier: '{s}'"))
    }
}

// ── CtaAction ─────────────────────────────────────────────────────────────────

/// Product template `cta_action` discriminant.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CtaAction {
    Waitlist,
    Signup,
    PreOrder,
    External,
    Anchor,
}

impl CtaAction {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Waitlist => "waitlist",
            Self::Signup => "signup",
            Self::PreOrder => "pre_order",
            Self::External => "external",
            Self::Anchor => "anchor",
        }
    }
}

impl fmt::Display for CtaAction {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for CtaAction {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s {
            "waitlist" => Ok(Self::Waitlist),
            "signup" | "/signup" => Ok(Self::Signup),
            "pre_order" | "pre-order" => Ok(Self::PreOrder),
            "external" => Ok(Self::External),
            "anchor" => Ok(Self::Anchor),
            other => Err(format!("unknown CtaAction: '{other}'")),
        }
    }
}

// ── VendorTradeKey ────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum VendorTradeKey {
    #[serde(rename = "cleaning")]
    Cleaning,
    #[serde(rename = "handyman")]
    Handyman,
    #[serde(rename = "plumbing")]
    Plumbing,
    #[serde(rename = "electrical")]
    Electrical,
    #[serde(rename = "hvac")]
    Hvac,
    #[serde(rename = "painting")]
    Painting,
    #[serde(rename = "landscaping")]
    Landscaping,
    #[serde(rename = "roofing")]
    Roofing,
    #[serde(rename = "flooring")]
    Flooring,
    #[serde(rename = "pest-control")]
    PestControl,
    #[serde(rename = "appliance")]
    Appliance,
    #[serde(rename = "locksmith")]
    Locksmith,
    #[serde(rename = "inspection")]
    Inspection,
    #[serde(rename = "movers")]
    Movers,
    #[serde(rename = "junk-removal")]
    JunkRemoval,
    #[serde(rename = "pool-spa")]
    PoolSpa,
    #[serde(rename = "security")]
    Security,
    #[serde(rename = "solar")]
    Solar,
    #[serde(rename = "general")]
    General,
}

impl VendorTradeKey {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Cleaning => "cleaning",
            Self::Handyman => "handyman",
            Self::Plumbing => "plumbing",
            Self::Electrical => "electrical",
            Self::Hvac => "hvac",
            Self::Painting => "painting",
            Self::Landscaping => "landscaping",
            Self::Roofing => "roofing",
            Self::Flooring => "flooring",
            Self::PestControl => "pest-control",
            Self::Appliance => "appliance",
            Self::Locksmith => "locksmith",
            Self::Inspection => "inspection",
            Self::Movers => "movers",
            Self::JunkRemoval => "junk-removal",
            Self::PoolSpa => "pool-spa",
            Self::Security => "security",
            Self::Solar => "solar",
            Self::General => "general",
        }
    }
}

impl fmt::Display for VendorTradeKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for VendorTradeKey {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s {
            "cleaning" => Ok(Self::Cleaning),
            "handyman" => Ok(Self::Handyman),
            "plumbing" => Ok(Self::Plumbing),
            "electrical" => Ok(Self::Electrical),
            "hvac" => Ok(Self::Hvac),
            "painting" => Ok(Self::Painting),
            "landscaping" => Ok(Self::Landscaping),
            "roofing" => Ok(Self::Roofing),
            "flooring" => Ok(Self::Flooring),
            "pest-control" => Ok(Self::PestControl),
            "appliance" => Ok(Self::Appliance),
            "locksmith" => Ok(Self::Locksmith),
            "inspection" => Ok(Self::Inspection),
            "movers" => Ok(Self::Movers),
            "junk-removal" => Ok(Self::JunkRemoval),
            "pool-spa" => Ok(Self::PoolSpa),
            "security" => Ok(Self::Security),
            "solar" => Ok(Self::Solar),
            "general" => Ok(Self::General),
            other => Err(format!("unknown VendorTradeKey: '{other}'")),
        }
    }
}

// ── BetaApplicantRole ─────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BetaApplicantRole {
    #[serde(rename = "landlord")]
    Landlord,
    #[serde(rename = "str-host")]
    StrHost,
    #[serde(rename = "broker")]
    Broker,
    #[serde(rename = "property-manager")]
    PropertyManager,
    #[serde(rename = "vendor")]
    Vendor,
}

impl BetaApplicantRole {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Landlord => "landlord",
            Self::StrHost => "str-host",
            Self::Broker => "broker",
            Self::PropertyManager => "property-manager",
            Self::Vendor => "vendor",
        }
    }
}

impl fmt::Display for BetaApplicantRole {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<&str> for BetaApplicantRole {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s {
            "landlord" => Ok(Self::Landlord),
            "str-host" => Ok(Self::StrHost),
            "broker" => Ok(Self::Broker),
            "property-manager" => Ok(Self::PropertyManager),
            "vendor" => Ok(Self::Vendor),
            other => Err(format!("unknown BetaApplicantRole: '{other}'")),
        }
    }
}
