//! GTM Landing Page Engine — discriminant enums
//!
//! All string-backed fields on `platform_products`, `product_page_variants`,
//! `product_tracking_pixels`, and `pub_products` lead-capture are expressed
//! here as proper Rust enums so the compiler enforces exhaustive match and
//! serde rejects unknown variants at deserialization boundaries.
//!
//! Pattern follows the existing codebase conventions in `types/lead.rs` and
//! `types/account.rs`:
//!   - `#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]`
//!   - `#[serde(rename_all = "snake_case")]` on the enum level
//!   - `impl Display` mapping each variant to its DB string
//!   - `impl TryFrom<String>` returning `Err(String)` on unknown discriminants

use std::fmt;
use serde::{Deserialize, Serialize};

// ── LaunchMode ────────────────────────────────────────────────────────────────

/// Controls what a visitor sees when they land on a product page.
///
/// Stored as VARCHAR in `platform_products.launch_mode` and
/// `product_page_variants.launch_mode`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LaunchMode {
    /// Product is fully live — show CTA to sign up / subscribe.
    Active,
    /// Product is in pre-launch — collect email for waitlist.
    Waitlist,
    /// Product is available for pre-order with Stripe Checkout.
    PreOrder,
    /// Internal soft-launch phase — shown only to approved testers.
    PreLaunch,
    /// Not yet ready for any traffic. Renders 404 / coming-soon.
    Draft,
}

impl LaunchMode {
    /// Returns `true` if visitors can complete a conversion action on the page.
    pub fn allows_conversion(&self) -> bool {
        matches!(self, Self::Active | Self::PreOrder | Self::Waitlist)
    }

    /// Returns `true` if the page should be indexed by search engines.
    pub fn is_indexable(&self) -> bool {
        matches!(self, Self::Active | Self::Waitlist | Self::PreOrder)
    }
}

impl fmt::Display for LaunchMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Active    => "active",
            Self::Waitlist  => "waitlist",
            Self::PreOrder  => "pre_order",
            Self::PreLaunch => "pre_launch",
            Self::Draft     => "draft",
        })
    }
}

impl TryFrom<String> for LaunchMode {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "active"     => Ok(Self::Active),
            "waitlist"   => Ok(Self::Waitlist),
            "pre_order"  => Ok(Self::PreOrder),
            "pre_launch" => Ok(Self::PreLaunch),
            "draft"      => Ok(Self::Draft),
            other        => Err(format!("unknown LaunchMode: '{other}'")),
        }
    }
}

impl TryFrom<&str> for LaunchMode {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── LocalizationStatus ────────────────────────────────────────────────────────

/// Tracks how a product page variant's copy was created / last modified.
///
/// Stored as VARCHAR in `product_page_variants.localization_status`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LocalizationStatus {
    /// Uses the base template copy — no market-specific overrides.
    Base,
    /// Copy was generated by the AI localization pipeline.
    AiLocalized,
    /// Copy was written or reviewed by a human marketer.
    Manual,
    /// AI localization task has been dispatched but not yet completed.
    Pending,
}

impl LocalizationStatus {
    /// Returns `true` if a human has reviewed or authored the copy.
    pub fn is_human_reviewed(&self) -> bool {
        matches!(self, Self::Manual)
    }
}

impl fmt::Display for LocalizationStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Base        => "base",
            Self::AiLocalized => "ai_localized",
            Self::Manual      => "manual",
            Self::Pending     => "pending",
        })
    }
}

impl TryFrom<String> for LocalizationStatus {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "base"         => Ok(Self::Base),
            "ai_localized" => Ok(Self::AiLocalized),
            "manual"       => Ok(Self::Manual),
            "pending"      => Ok(Self::Pending),
            other          => Err(format!("unknown LocalizationStatus: '{other}'")),
        }
    }
}

impl TryFrom<&str> for LocalizationStatus {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── CopyStrategy ──────────────────────────────────────────────────────────────

/// The approach used when generating this variant's copy.
///
/// Stored as VARCHAR in `product_page_variants.copy_strategy`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CopyStrategy {
    /// Market-specific copy: city, neighbourhood, local social proof.
    Localized,
    /// Verbatim copy from the base product template.
    BaseCopy,
    /// AI-generated using geo-context signals and product brief.
    AiGenerated,
}

impl fmt::Display for CopyStrategy {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Localized   => "localized",
            Self::BaseCopy    => "base_copy",
            Self::AiGenerated => "ai_generated",
        })
    }
}

impl TryFrom<String> for CopyStrategy {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "localized"    => Ok(Self::Localized),
            "base_copy"    => Ok(Self::BaseCopy),
            "ai_generated" => Ok(Self::AiGenerated),
            other          => Err(format!("unknown CopyStrategy: '{other}'")),
        }
    }
}

impl TryFrom<&str> for CopyStrategy {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── PixelType ─────────────────────────────────────────────────────────────────

/// The analytics / advertising platform a tracking snippet belongs to.
///
/// Stored as VARCHAR in `product_tracking_pixels.pixel_type` with a
/// CHECK constraint matching each variant's Display string.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PixelType {
    /// Google Tag Manager container.
    Gtm,
    /// Google Analytics 4 measurement ID (G-XXXXXXXX).
    Ga4,
    /// Meta (Facebook) Pixel.
    Meta,
    /// LinkedIn Insight Tag.
    Linkedin,
    /// TikTok Pixel.
    Tiktok,
    /// Any custom <script> or <noscript> block.
    Custom,
}

impl PixelType {
    /// Returns `true` if this pixel type requires a separate `<noscript>` fallback.
    pub fn needs_noscript_fallback(&self) -> bool {
        matches!(self, Self::Meta | Self::Linkedin)
    }
}

impl fmt::Display for PixelType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Gtm      => "gtm",
            Self::Ga4      => "ga4",
            Self::Meta     => "meta",
            Self::Linkedin => "linkedin",
            Self::Tiktok   => "tiktok",
            Self::Custom   => "custom",
        })
    }
}

impl TryFrom<String> for PixelType {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "gtm"      => Ok(Self::Gtm),
            "ga4"      => Ok(Self::Ga4),
            "meta"     => Ok(Self::Meta),
            "linkedin" => Ok(Self::Linkedin),
            "tiktok"   => Ok(Self::Tiktok),
            "custom"   => Ok(Self::Custom),
            other      => Err(format!("unknown PixelType: '{other}'")),
        }
    }
}

impl TryFrom<&str> for PixelType {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── InjectAt ──────────────────────────────────────────────────────────────────

/// Where in the HTML document a tracking snippet is injected.
///
/// Stored as VARCHAR in `product_tracking_pixels.inject_at`.
/// The SSR renderer reads this field to determine placement.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InjectAt {
    /// Inside `<head>` — recommended for most pixels (GTM, GA4, Meta).
    Head,
    /// Immediately after `<body>` opening tag.
    BodyStart,
    /// Immediately before `</body>` closing tag — for low-priority scripts.
    BodyEnd,
}

impl fmt::Display for InjectAt {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Head      => "head",
            Self::BodyStart => "body_start",
            Self::BodyEnd   => "body_end",
        })
    }
}

impl TryFrom<String> for InjectAt {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "head"       => Ok(Self::Head),
            "body_start" => Ok(Self::BodyStart),
            "body_end"   => Ok(Self::BodyEnd),
            other        => Err(format!("unknown InjectAt: '{other}'")),
        }
    }
}

impl TryFrom<&str> for InjectAt {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── PlanTier ──────────────────────────────────────────────────────────────────

/// Self-reported plan tier selected during a waitlist or trial signup.
///
/// Stored in `atlas_lead.lead_metadata` JSONB under the key `"plan"`.
/// Not persisted as a VARCHAR column because: (a) it's attribution metadata,
/// not a billing commitment; (b) pricing tiers change more often than DB schemas.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanTier {
    Starter,
    Professional,
    Portfolio,
}

impl PlanTier {
    /// Returns `true` if this tier suggests a high-value prospect worth
    /// immediate SDR follow-up (≥ Professional).
    pub fn is_high_value(&self) -> bool {
        matches!(self, Self::Professional | Self::Portfolio)
    }
}

impl fmt::Display for PlanTier {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Starter      => "starter",
            Self::Professional => "professional",
            Self::Portfolio    => "portfolio",
        })
    }
}

impl TryFrom<String> for PlanTier {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "starter"      => Ok(Self::Starter),
            "professional" => Ok(Self::Professional),
            "portfolio"    => Ok(Self::Portfolio),
            other          => Err(format!("unknown PlanTier: '{other}'")),
        }
    }
}

impl TryFrom<&str> for PlanTier {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── ResolutionType ────────────────────────────────────────────────────────────

/// The outcome of a domain/path resolution request.
///
/// Used in `handlers::pub_resolve::ResolveResponse` to let the Folio
/// frontend know which rendering path to take.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResolutionType {
    /// Resolved to a product-level master template page.
    Product,
    /// Resolved to a specific market variant page.
    Variant,
    /// Resolved to a tenant white-label app deployment.
    TenantApp,
    /// No product, variant, or tenant matched the request.
    NotFound,
}

impl fmt::Display for ResolutionType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Product   => "product",
            Self::Variant   => "variant",
            Self::TenantApp => "tenant_app",
            Self::NotFound  => "not_found",
        })
    }
}

impl TryFrom<String> for ResolutionType {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "product"    => Ok(Self::Product),
            "variant"    => Ok(Self::Variant),
            "tenant_app" => Ok(Self::TenantApp),
            "not_found"  => Ok(Self::NotFound),
            other        => Err(format!("unknown ResolutionType: '{other}'")),
        }
    }
}

impl TryFrom<&str> for ResolutionType {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

// ── AppId ──────────────────────────────────────────────────────────────────────

/// Identifies which Atlas app binary owns a given `platform_product`.
///
/// Values mirror the `&'static str` returned by each `AtlasApp::app_id()` impl.
/// Stored as `platform_products.app_slug` so the edge resolver can route
/// a domain request to the correct app SSR binary without slug-guessing.
///
/// # Keeping in sync
/// When a new `AtlasApp` impl is added in `atlas_apps/`, add its `app_id()` value
/// here AND update the DB CHECK constraint in the migration. The compiler will
/// flag every non-exhaustive match site automatically.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AppId {
    /// `FolioApp` — property management (LTR, STR, wholesaling)
    PropertyManagement,
    /// `AnchorApp` — anchor pages / classified directory
    Anchor,
    /// `NetworkInstanceApp` — network instance (portals, B2B directories)
    NetworkInstance,
    /// `MeridianApp` — hospitality / direct booking engine
    Meridian,
    /// `CorePlatformApp` — platform infrastructure (used for meta-products)
    CorePlatform,
}

impl AppId {
    /// The canonical string stored in the DB and returned in API responses.
    ///
    /// These must match the corresponding `AtlasApp::app_id()` return values.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::PropertyManagement => "property_management",
            Self::Anchor             => "anchor",
            Self::NetworkInstance    => "network_instance",
            Self::Meridian           => "meridian",
            Self::CorePlatform       => "core_platform",
        }
    }

    /// All valid DB values — used to generate the CHECK constraint in migrations.
    pub fn all_db_values() -> &'static [&'static str] {
        &[
            "property_management",
            "anchor",
            "network_instance",
            "meridian",
            "core_platform",
        ]
    }

    /// The marketing-facing slug used in URLs and product records.
    /// e.g. `PropertyManagement → "folio"`.
    pub fn product_slug(&self) -> &'static str {
        match self {
            Self::PropertyManagement => "folio",
            Self::Anchor             => "anchor",
            Self::NetworkInstance    => "network_instance",
            Self::Meridian           => "meridian",
            Self::CorePlatform       => "core",
        }
    }
}

impl fmt::Display for AppId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TryFrom<String> for AppId {
    type Error = String;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        match s.as_str() {
            "property_management" => Ok(Self::PropertyManagement),
            "anchor"              => Ok(Self::Anchor),
            "network_instance"    => Ok(Self::NetworkInstance),
            "meridian"            => Ok(Self::Meridian),
            "core_platform"       => Ok(Self::CorePlatform),
            other                 => Err(format!("unknown AppId: '{other}'")),
        }
    }
}

impl TryFrom<&str> for AppId {
    type Error = String;
    fn try_from(s: &str) -> Result<Self, Self::Error> {
        Self::try_from(s.to_string())
    }
}

