apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres.yaml
  - ingress.yaml
  - config.yaml

patches:
  - target:
      kind: Deployment
      name: network-instance
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "http://network.atlas.orb.local"
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "http://api.atlas.orb.local"
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: network-instance
    patch: |-
      - op: replace
        path: /spec/rules/1/host
        value: network.localhost
  - target:
      kind: Deployment
      name: platform-admin
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "http://admin.atlas.orb.local"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: API_URL
          value: "http://api.atlas.orb.local"
