use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

/// GENERIC-18: atlas_applications — Structured Intake & Onboarding Workflows
/// Rental applications, employment, mortgage, agency onboarding, creator tiers, etc.
#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(AtlasApplications::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(AtlasApplications::Id)
                            .uuid()
                            .not_null()
                            .primary_key()
                            .default(Expr::cust("gen_random_uuid()")),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::TenantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::ApplicationType)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::ApplicantUserId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::TargetAssetId)
                            .uuid()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::TargetOpportunityId)
                            .uuid()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::TargetProgram)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::Status)
                            .string()
                            .not_null()
                            .default(Expr::val("draft")),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::PrimaryApplicationId)
                            .uuid()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::MonthlyIncomeCents)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::IncomeCurrency)
                            .char_len(3)
                            .not_null()
                            .default(Expr::val("USD")),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::NationalIdType)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::NationalIdLast4)
                            .string_len(4)
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::ScreeningStatus)
                            .string()
                            .not_null()
                            .default(Expr::val("not_started")),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::ScreeningProvider)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::ScreeningPassed)
                            .boolean()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::DisclosuresAccepted)
                            .json_binary()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::ApplicationMetadata)
                            .json_binary()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::SubmittedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::DecidedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::DecisionReason)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::ResultingContractId)
                            .uuid()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(AtlasApplications::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_atlas_applications_tenant_type_status")
                    .table(AtlasApplications::Table)
                    .col(AtlasApplications::TenantId)
                    .col(AtlasApplications::ApplicationType)
                    .col(AtlasApplications::Status)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_atlas_applications_applicant")
                    .table(AtlasApplications::Table)
                    .col(AtlasApplications::ApplicantUserId)
                    .col(AtlasApplications::Status)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_atlas_applications_asset")
                    .table(AtlasApplications::Table)
                    .col(AtlasApplications::TargetAssetId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_atlas_applications_primary")
                    .table(AtlasApplications::Table)
                    .col(AtlasApplications::PrimaryApplicationId)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(AtlasApplications::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum AtlasApplications {
    Table,
    Id,
    TenantId,
    ApplicationType,
    ApplicantUserId,
    TargetAssetId,
    TargetOpportunityId,
    TargetProgram,
    Status,
    PrimaryApplicationId,
    MonthlyIncomeCents,
    IncomeCurrency,
    NationalIdType,
    NationalIdLast4,
    ScreeningStatus,
    ScreeningProvider,
    ScreeningPassed,
    DisclosuresAccepted,
    ApplicationMetadata,
    SubmittedAt,
    DecidedAt,
    DecisionReason,
    ResultingContractId,
    CreatedAt,
}
