use sea_orm_migration::prelude::*;

/// Create `atlas_invite_codes` — short-token invite system for deep-link provisioning.
///
/// An invite code is a human-readable token that pre-resolves all the context
/// needed to provision a new user into a specific role + entity relationship.
///
/// ## Core Use Cases
///
///   "Apply for THIS apartment"
///     → role=tenant, asset_id=<unit>, landlord_id=<PM>, max_uses=unlimited
///
///   "You're here to repair THIS unit"
///     → role=vendor, asset_id=<unit>, landlord_id=<PM>, max_uses=1
///
///   "Book this STR property"
///     → role=str_guest, asset_id=<property>, max_uses=unlimited, expiry=listing_end
///
///   "Join as a cohost for this portfolio"
///     → role=cohost, landlord_id=<owner>, max_uses=5
///
///   "You're an agent at this brokerage"
///     → role=agent, broker_id=<broker>, max_uses=unlimited
///
/// ## Resolution Flow
///   GET /join/{code}
///   → resolve code → role + context
///   → redirect to /folio/onboard/{role}?code={code}
///   → wizard left panel shows resolved entity name + message
///   → on completion, platform_invite is created with all resolved FKs
///   → uses_count incremented; deactivated when uses_count >= max_uses
///
/// ## Code Format
///   Generated by the platform or landlord:
///   - Human-readable prefix + random suffix: "OAK4B-K7X", "VILLA-2025", "WO-A93F"
///   - Platform-admin may use UUID-short: "inv_a3b9c7d1"
///   - Max 16 chars to be easily typeable and fit in a QR scan
///
#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r#"CREATE TABLE IF NOT EXISTS atlas_invite_codes (
                    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
                    -- The short code shown to users / embedded in QR codes / links
                    code            VARCHAR(16) NOT NULL UNIQUE,
                    -- Workspace this code belongs to
                    workspace_id    UUID        NOT NULL,
                    -- Which role this code provisions
                    role            VARCHAR(30) NOT NULL
                                    CHECK (role IN (
                                        'landlord', 'tenant', 'str_guest', 'vendor',
                                        'cohost', 'owner', 'property_manager', 'agent', 'broker'
                                    )),

                    -- Context references (all nullable; validation enforced by handler)
                    -- A single asset (most common: one apartment, one vacation property)
                    asset_id        UUID        REFERENCES atlas_assets(id) ON DELETE SET NULL,
                    -- Multiple assets (landlord delegating a whole portfolio to a cohost/vendor)
                    -- Stored as a comma-separated list of UUIDs; parsed in application layer.
                    -- Ideally would be UUID[] but we keep migration portable without extensions.
                    asset_ids_csv   TEXT,
                    -- STR booking this code is pre-linked to
                    booking_id      UUID        REFERENCES atlas_bookings(id) ON DELETE SET NULL,
                    -- The landlord / property manager who owns the assets
                    landlord_id     UUID        REFERENCES "user"(id) ON DELETE SET NULL,
                    -- The broker who is sponsoring the agent (agent role only)
                    broker_id       UUID        REFERENCES "user"(id) ON DELETE SET NULL,

                    -- Who created this invite code
                    created_by      UUID        NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,

                    -- Usage control
                    -- NULL max_uses = unlimited (e.g., "for-rent sign" QR)
                    max_uses        INT,
                    uses_count      INT         NOT NULL DEFAULT 0,
                    expires_at      TIMESTAMPTZ,
                    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,

                    -- UX metadata shown in onboarding wizard
                    -- Human-readable label displayed in the wizard's left context panel
                    label           TEXT,
                    -- Custom message from the inviter shown in the wizard header
                    invite_message  TEXT,
                    -- Extra KV data for future extensibility (commission pct, unit notes, etc.)
                    metadata        JSONB,

                    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );

                -- Fast lookups by code (most common query path)
                CREATE INDEX IF NOT EXISTS idx_invite_codes_code
                    ON atlas_invite_codes(code);

                -- Let workspace admins list their codes efficiently
                CREATE INDEX IF NOT EXISTS idx_invite_codes_workspace
                    ON atlas_invite_codes(workspace_id);

                -- Landlord can see all codes they created
                CREATE INDEX IF NOT EXISTS idx_invite_codes_created_by
                    ON atlas_invite_codes(created_by);

                -- Asset-scoped codes (e.g., all codes for a given unit)
                CREATE INDEX IF NOT EXISTS idx_invite_codes_asset
                    ON atlas_invite_codes(asset_id)
                    WHERE asset_id IS NOT NULL;
                "#,
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared(
                r#"DROP INDEX IF EXISTS idx_invite_codes_asset;
                   DROP INDEX IF EXISTS idx_invite_codes_created_by;
                   DROP INDEX IF EXISTS idx_invite_codes_workspace;
                   DROP INDEX IF EXISTS idx_invite_codes_code;
                   DROP TABLE IF EXISTS atlas_invite_codes;
                "#,
            )
            .await?;

        Ok(())
    }
}
