use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Add subdomain and custom_domain fields to the network table
        manager
            .alter_table(
                Table::alter()
                    .table(Network::Table)
                    .add_column(
                        ColumnDef::new(Network::Subdomain)
                            .string()
                            .null()
                            .unique_key()
                    )
                    .add_column(
                        ColumnDef::new(Network::CustomDomain)
                            .string()
                            .null()
                            .unique_key()
                    )
                    .add_column(
                        ColumnDef::new(Network::Logo)
                            .string()
                            .null()
                    )
                    .add_column(
                        ColumnDef::new(Network::Favicon)
                            .string()
                            .null()
                    )
                    .add_column(
                        ColumnDef::new(Network::HeaderScripts)
                            .string()
                            .null()
                    )
                    .add_column(
                        ColumnDef::new(Network::FooterScripts)
                            .string()
                            .null()
                    )
                    .add_column(
                        ColumnDef::new(Network::GoogleAnalyticsId)
                            .string()
                            .null()
                    )
                    .add_column(
                        ColumnDef::new(Network::GoogleSiteVerification)
                            .string()
                            .null()
                    )
                    .add_column(
                        ColumnDef::new(Network::MetaDescription)
                            .text()
                            .null()
                    )
                    .add_column(
                        ColumnDef::new(Network::MetaKeywords)
                            .text()
                            .null()
                    )
                    .add_column(
                        ColumnDef::new(Network::MetaTitle)
                            .text()
                            .null()
                    )
                    .add_column(
                        ColumnDef::new(Network::PageTitle)
                            .string()
                            .null()
                    )
                    .add_column(
                        ColumnDef::new(Network::PageDescription)
                            .string()
                            .null()
                    )
                    .add_column(
                        ColumnDef::new(Network::PageKeywords)
                            .string()
                            .null()
                    )
                    .add_column(
                        ColumnDef::new(Network::CanonicalUrl)
                            .text()
                            .null()
                    )
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Remove the added columns
        manager
            .alter_table(
                Table::alter()
                    .table(Network::Table)
                    .drop_column(Network::Subdomain)
                    .drop_column(Network::CustomDomain)
                    .drop_column(Network::Logo)
                    .drop_column(Network::Favicon)
                    .drop_column(Network::HeaderScripts)
                    .drop_column(Network::FooterScripts)
                    .drop_column(Network::GoogleAnalyticsId)
                    .drop_column(Network::GoogleSiteVerification)
                    .drop_column(Network::MetaDescription)
                    .drop_column(Network::MetaKeywords)
                    .drop_column(Network::MetaTitle)
                    .drop_column(Network::PageTitle)
                    .drop_column(Network::PageDescription)
                    .drop_column(Network::PageKeywords)
                    .drop_column(Network::CanonicalUrl)
                    .to_owned(),
            )
            .await
    }
}

#[derive(Iden)]
enum Network {
    Table,
    Subdomain,
    CustomDomain,
    Logo,
    Favicon,
    HeaderScripts,
    FooterScripts,
    GoogleAnalyticsId,
    GoogleSiteVerification,
    MetaDescription,
    MetaKeywords,
    MetaTitle,
    PageTitle,
    PageDescription,
    PageKeywords,
    CanonicalUrl,
} 