apiVersion: apps/v1
kind: Deployment
metadata:
  name: anchor-app
  namespace: anchor
spec:
  template:
    spec:
      containers:
      - name: anchor-app
        imagePullPolicy: Always
      # We append the imagePullSecrets parameter so K8s knows how to parse GHCR!
      imagePullSecrets:
      - name: ghcr-login-secret
