apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: buildwithruud-uat
resources:
  - ../../../base
  - config.yaml
  - ingress.yaml

# Kustomize natively swaps the image URI from the 'base' config to your remote registry URI
images:
  - name: anchor-app:latest
    newName: ghcr.io/ruuderie/anchor-app
    newTag: latest

# Apply the patch to inject the pull secrets credential into the deployment
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: anchor-app
