apiVersion: ENC[AES256_GCM,data:Os0=,iv:jMWSfEGQafAi2InWyA6mCp6HzG7JXfJf9Jg1QobWZ94=,tag:je7DinsLm+GqUkGUmKdbEQ==,type:str]
kind: ENC[AES256_GCM,data:Y6exAAcP,iv:tzCODhX3F+eBlut2x3yP6XZeksXFmJ/dHwtDY0GDVL0=,tag:TNCUa9LcQ3EfZZt41Gwwow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DVAqRlYkBipT8Rk=,iv:f/ji7OxGwGSBPTq4h2SiukydQ5QUzoqcQiKjMiQP2XM=,tag:QgcBhVe88J0w3d+cYeWPug==,type:str]
    namespace: ENC[AES256_GCM,data:oGQohPqY56kKg4N2bNpbVkw=,iv:H2yujobf1d5YWpAQT2prKnJn3+EdjeGaXDXlGw3B9Ro=,tag:/K9Ml/cM0VyYPjpoohJqZw==,type:str]
type: ENC[AES256_GCM,data:/5BqK/ag,iv:N+vWZqPEaNFxP6hGlblDO6UmfLKjHkmyyBKxF3Bb/WA=,tag:AzCAPqMEGVoFintexb1BIw==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:3wdt7xN6C/0k32eMn6xcuXdHbR79pe/KuISbKMboYTOV1dIERr0EtZKqNJxMBmNmPj6giIk4BSUwP00f7jllbL5lwKgPvQpx2RbZlmPxgw==,iv:FufS9fNdbMu1pTGBZMWtuDLTzOaPv7yZF/QQJ1EvVgk=,tag:78iUM14FJZt2rg7aL6NBUg==,type:str]
sops:
    age:
        - recipient: age1sm0da8e769n8nvjh9f44a90qk984f7axzzs56l9l2ncmac47qacszcvppe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWjVRWXdhRUNhNFpTenc4
            K1NVOHkvdHlBQ3JXTS9VUktXbWRSeG16U2w4CmVJNlVzcFBPTUwzK2xiaHczQ2RE
            dWNXdWxEUTJrSkZJMGQvYzdXV1FVTHMKLS0tIGM4TDlha1U3NGFSMW1nUXJyTmU1
            dkd6MGozSTk4ajQveXVveFZOenhETTAKSRNQ6PeSyXNJDWA4CEnGu1Bul/9zkr3j
            PrRFmTw/WX9QxQ0vL41ymHfw0lHgFu2qxhHq2C6G6mcCftth3JKynA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T00:11:28Z"
    mac: ENC[AES256_GCM,data:yHpvZjVFZs439J8RjkfzTkL4yzPvRwpfc7T30XVZA/yDIvemjvUEybBRemVcSUjabOEsLnILMJ6tSuJnLBbS/Oc+sFr+FrL7eEuP3SgOxAhI/ExUhPsiB2n9xlk3XbjxS++5H8JDPYr52MmuYUwLmZREui7sD9Sz/TbscxWiKAw=,iv:m9AwQTdH8fmIJX8tHKZqKJ9V7X51k03Pu26BBj6/CDQ=,tag:nsJStWBYcl0dItMnsVWXEA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
