/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.rs",
    "../shared-ui/src/**/*.rs",
    "./index.html"
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#5b74b1",
        "error-container": "#7f2927",
        "surface-dim": "#060e20",
        "tertiary-fixed": "#65fde6",
        "on-secondary-container": "#b1c0d6",
        "on-secondary": "#122131",
        "secondary-dim": "#909fb4",
        "on-primary-container": "#97d8ff",
        "surface-container-high": "#031d4b",
        "on-tertiary-fixed": "#004a41",
        "secondary-fixed": "#d4e4fa",
        "surface-container": "#05183c",
        "on-tertiary": "#00685c",
        "on-primary-fixed-variant": "#006286",
        "inverse-surface": "#faf8ff",
        "error-dim": "#bb5551",
        "on-background": "#dee5ff",
        "primary-dim": "#47c4ff",
        "on-secondary-fixed-variant": "#4e5d6f",
        "on-primary-fixed": "#00445e",
        "on-surface-variant": "#91aaeb",
        "on-secondary-fixed": "#324052",
        "tertiary-container": "#65fde6",
        "secondary": "#909fb4",
        "surface": "#060e20",
        "tertiary": "#c6fff3",
        "on-error-container": "#ff9993",
        "secondary-container": "#2e3c4e",
        "primary-fixed": "#c4e7ff",
        "on-tertiary-container": "#005e54",
        "tertiary-fixed-dim": "#54eed8",
        "on-primary": "#004560",
        "surface-tint": "#7bd0ff",
        "surface-bright": "#002867",
        "inverse-primary": "#00668b",
        "surface-variant": "#00225a",
        "background": "#060e20",
        "surface-container-lowest": "#000000",
        "primary-fixed-dim": "#a2dcff",
        "on-surface": "#dee5ff",
        "tertiary-dim": "#54eed8",
        "surface-container-highest": "#00225a",
        "on-tertiary-fixed-variant": "#00695e",
        "outline-variant": "#2b4680",
        "primary": "#7bd0ff",
        "secondary-fixed-dim": "#c6d6ec",
        "inverse-on-surface": "#4d556b",
        "surface-container-low": "#06122d",
        "primary-container": "#004c69",
        "on-error": "#490106",
        "error": "#ee7d77",
        // Legacy compat keys for shared-ui components
        "foreground": "#dee5ff",
        "card": {
          DEFAULT: "#05183c",
          foreground: "#dee5ff",
        },
        "popover": {
          DEFAULT: "#05183c",
          foreground: "#dee5ff",
        },
        "muted": {
          DEFAULT: "#06122d",
          foreground: "#91aaeb",
        },
        "accent": {
          DEFAULT: "#031d4b",
          foreground: "#dee5ff",
        },
        "destructive": {
          DEFAULT: "#ee7d77",
          foreground: "#060e20",
        },
        "border": "#2b4680",
        "input": "#2b4680",
        "ring": "#7bd0ff",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [],
}
