apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-instance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: network-instance
  template:
    metadata:
      labels:
        app: network-instance
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: network-instance
        image: ghcr.io/ruuderie/network-instance:latest
        ports:
        - containerPort: 8080
        env:
        # Example API binding
        - name: API_URL
          value: "http://backend:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: network-instance
spec:
  selector:
    app: network-instance
  ports:
  - port: 80
    targetPort: 8080
