apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-admin
  template:
    metadata:
      labels:
        app: platform-admin
    spec:
      containers:
      - name: platform-admin
        image: ghcr.io/ruuderie/platform-admin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: platform-admin
spec:
  selector:
    app: platform-admin
  ports:
  - port: 80
    targetPort: 80