apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlas-dev

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - config.yaml

patches:
  - path: platform-admin-patch.yaml
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/envFrom/2
  - path: backend-patch.yaml
