/** @type {import('tailwindcss').Config} */
module.exports = {
  content: {
    files: ["*.html", "./src/**/*.rs"],
  },
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2d1600",
        "primary-fixed-dim": "#88cffd",
        "on-tertiary-fixed-variant": "#6a3b00",
        "surface-variant": "#e1e3e3",
        "secondary": "#ab3506",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#8a510b",
        "inverse-primary": "#88cffd",
        "on-secondary-container": "#621900",
        "tertiary-fixed-dim": "#ffb873",
        "background": "#f8fafa",
        "surface-container-highest": "#e1e3e3",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eff1f1",
        "tertiary-fixed": "#ffdcbf",
        "on-primary-fixed": "#001e2e",
        "surface-tint": "#00658e",
        "on-primary-container": "#b1deff",
        "on-secondary-fixed": "#3a0b00",
        "primary-fixed": "#c7e7ff",
        "tertiary": "#6a3c00",
        "outline-variant": "#bfc7cf",
        "primary": "var(--color-primary, #004c6c)",
        "surface-dim": "#d8dada",
        "surface": "#f8fafa",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#004c6c",
        "inverse-surface": "#2e3131",
        "on-secondary-fixed-variant": "#842500",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffdbd0",
        "secondary-container": "#fd7040",
        "primary-container": "var(--color-primary-container, #00658e)",
        "surface-container-low": "#f2f4f4",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#ffb59e",
        "surface-bright": "#f8fafa",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e8e9",
        "on-surface": "#191c1d",
        "surface-container": "#eceeee",
        "outline": "#70787f",
        "on-background": "#191c1d",
        "on-tertiary-container": "#ffd0a7",
        "on-surface-variant": "#40484e",
        "on-primary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "sans": ["Inter", "sans-serif"],
        "display": ["Newsreader", "serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "label": ["Inter"],
        "jetbrains": ["JetBrains Mono", "monospace"]
      },

    },
  },
  plugins: [],
}
