apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlas-platform

resources:
  - ../../base
  - ingress.yaml
  - config.yaml

patches:
  - path: platform-admin-patch.yaml
  - path: backend-patch.yaml
