apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlas-uat

resources:
  - ../../base
  # namespace.yaml applied once by admin — not managed by CI
  - ingress.yaml
  - config.yaml

patches:
  - path: platform-admin-patch.yaml
  - path: backend-patch.yaml
